package dev.toastbits.lifelog.application.settings.domain.group

import dev.toastbits.composekit.platform.preferences.impl.group.ComposeKitInterfacePreferencesGroup

interface InterfacePreferencesGroup: ComposeKitInterfacePreferencesGroup
